fieldLayouts:
  8b365252-6d01-4e59-b381-719ddb6315d2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 6886ced7-26db-4655-8dd3-168775766275
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 28c373e6-6c56-4c40-a9d6-8480fc9f5602
        userCondition: null
fs: uploads2
handle: cloudUploads2
name: 'Cloud Uploads 2'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
