fieldLayouts:
  43490f59-8224-4093-af3e-e9d8d79bbd43:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: fc2ee823-e7e0-427b-9e50-f5117ed2df79
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0f53799c-1e8f-4634-9efc-e12eb084caa4
        userCondition: null
fs: localUploads2
handle: localUploads2
name: 'Local Uploads 2'
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
