columnSuffix: null
handle: richText
instructions: null
name: 'RIch Text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: c6bc4011-a333-44fb-a74a-fd8c85589e3f # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
