dateModified: 1743779181
email:
  fromEmail: tim@craftcms.com
  fromName: 'Craft Project'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      expires: '1 years'
      hasUrls: true
      localFsPath: '@webroot/uploads'
      localFsUrl: /uploads
      subpath: null
    type: craft\cloud\fs\AssetsFs
meta:
  __names__:
    1c4db2bd-b409-4bf2-a56e-c3327f0b160e: 'Craft Project' # Craft Project
    81a6b84b-4e06-4828-a256-d2d537885644: Common # Common
    283a253c-a365-4823-89c4-b48fbd2232a3: 'Craft Project' # Craft Project
    b0a49e7b-8490-450c-ba0b-8f2ae4ddd49c: Uploads # Uploads
plugins:
  google-maps:
    edition: standard
    enabled: true
    schemaVersion: 4.6.0
system:
  edition: pro
  live: true
  name: 'Craft Project'
  schemaVersion: 4.15.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
