dateModified: 1710469187
elementSources:
  craft\elements\Asset:
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:ebb28449-0c0f-4753-b7f0-2a386651d786' # Cloud Uploads
      tableAttributes:
        - filename
        - size
        - dateModified
        - uploader
        - link
      type: native
    -
      key: 'volume:b7ffbdbb-b407-4351-9c22-b6b7f6925625' # Cloud Uploads 2
      type: native
    -
      key: 'volume:12ebe9f9-bff1-4728-b9ce-4bfee2128ada' # Local Uploads
      type: native
    -
      key: 'volume:a5c039a6-2a22-4ab8-ba94-ae0b05659989' # Local Uploads 2
      type: native
    -
      key: 'folder:fd912745-4661-4156-ae9e-0706f35d6507'
      type: native
    -
      condition:
        class: craft\elements\conditions\assets\AssetCondition
        elementType: craft\elements\Asset
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:b7f54890-11dd-4b6f-bd09-5b1688a8aa20'
      label: adad
      tableAttributes:
        - filename
        - size
      type: custom
email:
  fromEmail: tim@craftcms.com
  fromName: 'Craft Project'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  localUploads:
    hasUrls: true
    name: 'Local Uploads'
    settings:
      path: '@webroot/uploads-local'
    type: craft\fs\Local
    url: '@web/uploads-local'
  localUploads2:
    hasUrls: true
    name: 'Local Uploads 2'
    settings:
      path: '@webroot/uploads2-local'
    type: craft\fs\Local
    url: '@webroot/uploads2-local'
  uploads:
    hasUrls: true
    name: 'Cloud Uploads'
    settings:
      expires: '1 years'
      hasUrls: true
      localFsPath: '@webroot/uploads'
      localFsUrl: '@web/uploads'
      subpath: uploads
    type: craft\cloud\fs\AssetsFs
  uploads2:
    hasUrls: true
    name: 'Cloud Uploads 2'
    settings:
      expires: '1 years'
      hasUrls: true
      localFsPath: '@webroot/uploads2'
      localFsUrl: '@web/uploads2'
      subpath: uploads2
    type: craft\cloud\fs\AssetsFs
meta:
  __names__:
    4ef24029-7efa-4c7d-8931-9421b4ed9531: Common # Common
    12ebe9f9-bff1-4728-b9ce-4bfee2128ada: 'Local Uploads' # Local Uploads
    051a1185-077a-436b-ba21-9b387f9e5792: Blog # Blog
    55f51928-0140-4cc4-8297-8eb1c75aa137: Assets # Assets
    a5c039a6-2a22-4ab8-ba94-ae0b05659989: 'Local Uploads 2' # Local Uploads 2
    ae206acc-928e-48f2-b2ad-e0fe0c5fd4ff: Default # Default
    b7ffbdbb-b407-4351-9c22-b6b7f6925625: 'Cloud Uploads 2' # Cloud Uploads 2
    ebb28449-0c0f-4753-b7f0-2a386651d786: 'Cloud Uploads' # Cloud Uploads
    f89ec9e3-4a4e-4a64-8c8c-3bb3673e4729: 'Craft Project' # Craft Project
    fd87c458-a1fd-4795-bf33-cd7f1eb0f1de: 'Craft Project' # Craft Project
system:
  edition: pro
  live: true
  name: 'Craft Project'
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
